#pragma once
#include "PiranhaPlant.h"

#define FIRE_PIRANHA_PLANT_GREEN 0
#define FIRE_PIRANHA_PLANT_RED 1

#define FIRE_PIRANHA_PLANT_TL 0
#define FIRE_PIRANHA_PLANT_BL 1
#define FIRE_PIRANHA_PLANT_TR 2
#define FIRE_PIRANHA_PLANT_BR 3

#define FIRE_PIRANHA_PLANT_GREEN_RISING_HEIGHT 24
#define FIRE_PIRANHA_PLANT_RED_RISING_HEIGHT 32

#define FIRE_PIRANHA_PLANT_RISING_TIME 500
#define FIRE_PIRANHA_PLANT_WAITING_TIME 1200

//Animation Ids
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_TL_IDLE 50031
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_TL_RISING 50032
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_BL_IDLE 50041
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_BL_RISING 50042
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_TR_IDLE 50051
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_TR_RISING 50052
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_BR_IDLE 50061
#define FIRE_PIRANHA_PLANT_GREEN_ANIMATION_BR_RISING 50062

#define FIRE_PIRANHA_PLANT_RED_ANIMATION_TL_IDLE 50071
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_TL_RISING 50072
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_BL_IDLE 50081
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_BL_RISING 50082
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_TR_IDLE 50091
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_TR_RISING 50092
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_BR_IDLE 50101
#define FIRE_PIRANHA_PLANT_RED_ANIMATION_BR_RISING 50102

class CFirePiranhaPlant : public CPiranhaPlant
{
	int type;
	int direction;		//0: Top left	1: Bottom left	2: Top right	3: Bottom right
public:
	CFirePiranhaPlant(float x, float y, int type) : CPiranhaPlant(x, y) {
		this->type = type;
		switch (type) {
		case FIRE_PIRANHA_PLANT_GREEN:
			risingHeight = FIRE_PIRANHA_PLANT_GREEN_RISING_HEIGHT;
			break;
		case FIRE_PIRANHA_PLANT_RED:
			risingHeight = FIRE_PIRANHA_PLANT_RED_RISING_HEIGHT;
			break;
		}
		risingTime = FIRE_PIRANHA_PLANT_RISING_TIME;
		waitingTime = FIRE_PIRANHA_PLANT_WAITING_TIME;
	}
	void Render();
	void Update(DWORD dt);
	void GetBoundingBox(float& left, float& top, float& right, float& bottom);
	void OnCollisionWith(LPCOLLISIONEVENT e) {};
};

